<?php

/**
 * @file
 * OpenEuropa Translation Poetry Mock module file.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_translation_poetry_mock_theme($existing, $type, $theme, $path) {
  return [
    'status_notification' => [
      'variables' => [
        'request_identifier' => [],
        'request_status' => NULL,
        'accepted_languages' => [],
        'refused_languages' => [],
        'cancelled_languages' => [],
      ],
    ],
  ];
}
