<?php

/**
 * @file
 * OpenEuropa Translation Block Field module file.
 */

declare(strict_types = 1);

use Drupal\oe_translation_block_field\BlockFieldProcessor;

/**
 * Implements hook_field_info_alter().
 */
function oe_translation_block_field_field_info_alter(&$info) {
  if (isset($info['block_field'])) {
    $info['block_field']['oe_translation_source_field_processor'] = BlockFieldProcessor::class;
  }
}
