clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_translation

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment: &web-environment
      - DOCUMENT_ROOT=/test/oe_translation
      - COMPOSERVER=--2
      - EPOETRY_SERVICE_URL=http://web:8080/build/epoetry-mock/server
      - EPOETRY_APPLICATION_NAME=digit
      - EPOETRY_AUTH_CERT_SERVICE_URL=""
      - EPOETRY_AUTH_CERT_PATH=""
      - EPOETRY_AUTH_CERT_PASSWORD=""
      - EPOETRY_AUTH_EU_LOGIN_BASEPATH=""
      - CDT_TOKEN_API_ENDPOINT=https://example.com/token
      - CDT_MAIN_API_ENDPOINT=https://example.com/v2/CheckConnection
      - CDT_REFERENCE_DATA_API_ENDPOINT=https://example.com/v2/requests/businessReferenceData
      - CDT_VALIDATE_API_ENDPOINT=https://example.com/v2/requests/validate
      - CDT_REQUESTS_API_ENDPOINT=https://example.com/v2/requests
      - CDT_IDENTIFIER_API_ENDPOINT=https://example.com/v2/requests/requestIdentifierByCorrelationId/:correlationId
      - CDT_STATUS_API_ENDPOINT=https://example.com/v2/requests/:requestyear/:requestnumber
      - CDT_FILE_API_ENDPOINT=https://example.com/v2/requests/:requestyear/:requestnumber/targets-base64
      - CDT_CLIENT=test_client
      - CDT_USERNAME=test_username
      - CDT_PASSWORD=test_password
      - CDT_API_KEY=test_api_key
  mysql:
    image: git.fpfis.tech.ec.europa.eu/fpfis/dependency_proxy/containers/percona:5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: git.fpfis.tech.ec.europa.eu/fpfis/dependency_proxy/containers/selenium/standalone-chrome:4.1.3-20220405
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - apt update -y
      - apt install php${PHP_VERSION}-bcmath -y
      - composer self-update --2
      - composer require drupal/core:~${CORE_VERSION} drupal/core-composer-scaffold:~${CORE_VERSION} drupal/core-dev:~${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction

  ensure-phpunit-batching:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit --group default
    environment: *web-environment

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment: *web-environment
    commands:
      - ./vendor/bin/phpunit --group $BATCH

  debug:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure

matrix:
  include:
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.2.0, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.2.0, TYPE: phpunit, BATCH: batch2 }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.3.0, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.3.0, TYPE: phpunit, BATCH: batch2 }
    - { PHP_VERSION: 8.2, CORE_VERSION: 10.2.0, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 8.2, CORE_VERSION: 10.2.0, TYPE: phpunit, BATCH: batch2 }
    - { PHP_VERSION: 8.2, CORE_VERSION: 10.3.0, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 8.2, CORE_VERSION: 10.3.0, TYPE: phpunit, BATCH: batch2 }
