<?php

/**
 * @file
 * OpenEuropa Translation install file.
 */

use Drupal\Core\Config\Entity\ConfigEntityType;
use Drupal\Core\Entity\ContentEntityType;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\oe_translation\Entity\TranslationRequest;
use Drupal\oe_translation\Entity\TranslationRequestLog;
use Drupal\oe_translation\Entity\TranslationRequestType;

/**
 * Creates the revision ID field on the TMGMT job item entity.
 */
function oe_translation_update_8001(&$sandbox) {
  $field = BaseFieldDefinition::create('integer')
    ->setLabel(new TranslatableMarkup('Item revision ID'))
    ->setSetting('unsigned', TRUE);

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('item_rid', 'tmgmt_job_item', 'oe_translation', $field);
}

/**
 * Creates the Item bundle field on the TMGMT job item entity.
 */
function oe_translation_update_8002(&$sandbox) {
  $field = BaseFieldDefinition::create('string')
    ->setLabel(new TranslatableMarkup('Item bundle'));

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('item_bundle', 'tmgmt_job_item', 'oe_translation', $field);
}

/**
 * Installs new entity types and modules.
 */
function oe_translation_update_9001(): void {
  // Install the new entity types.
  $update_manager = \Drupal::entityDefinitionUpdateManager();
  $translation_request_entity_type = [
    'id' => 'oe_translation_request',
    'label' => new TranslatableMarkup('Translation Request'),
    'label_collection' => new TranslatableMarkup('Translation Requests'),
    'bundle_label' => new TranslatableMarkup('Translation Request type'),
    'handlers' => [
      'list_builder' => 'Drupal\oe_translation\TranslationRequestListBuilder',
      'views_data' => 'Drupal\views\EntityViewsData',
      'access' => 'Drupal\oe_translation\Access\TranslationRequestAccessControlHandler',
      'form' => [
        'default' => 'Drupal\oe_translation\Form\TranslationRequestForm',
        'add' => 'Drupal\oe_translation\Form\TranslationRequestForm',
        'edit' => 'Drupal\oe_translation\Form\TranslationRequestForm',
        'delete' => 'Drupal\Core\Entity\ContentEntityDeleteForm',
      ],
      'route_provider' => [
        'html' => 'Drupal\oe_translation\Routing\TranslationRequestRouteProvider',
      ],
    ],
    'base_table' => 'oe_translation_request',
    'admin_permission' => 'administer translation requests',
    'entity_keys' => [
      'id' => 'id',
      'bundle' => 'bundle',
      'label' => 'id',
      'uuid' => 'uuid',
      'created' => 'created',
      'changed' => 'changed',
      'published' => 'status',
      'owner' => 'uid',
    ],
    'links' => [
      'add-form' => '/translation-request/add/{oe_translation_request_type}',
      'add-page' => '/translation-request/add',
      'canonical' => '/translation-request/{oe_translation_request}',
      'collection' => '/admin/content/translation-request',
      'edit-form' => '/translation-request/{oe_translation_request}/edit',
      'delete-form' => '/translation-request/{oe_translation_request}/delete',
      'delete-multiple-form' => '/admin/content/translation-requests/delete',
      'preview' => "/translation-request/{oe_translation_request}/preview/{language}",
    ],
    'bundle_entity_type' => 'oe_translation_request_type',
    'field_ui_base_route' => 'entity.oe_translation_request_type.edit_form',
  ];

  $translation_request_log_entity_type = [
    'id' => 'oe_translation_request_log',
    'label' => new TranslatableMarkup('Translation request log'),
    'base_table' => 'oe_translation_request_log',
    'entity_keys' => [
      'id' => 'id',
      'label' => 'id',
      'uuid' => 'uuid',
      'owner' => 'uid',
    ],
  ];
  $translation_request_config_entity_type = [
    'id' => 'oe_translation_request_type',
    'label' => new TranslatableMarkup('Translation Request type'),
    'handlers' => [
      'form' => [
        'add' => 'Drupal\oe_translation\Form\TranslationRequestTypeForm',
        'edit' => 'Drupal\oe_translation\Form\TranslationRequestTypeForm',
        'delete' => 'Drupal\Core\Entity\EntityDeleteForm',
      ],
      'list_builder' => 'Drupal\oe_translation\TranslationRequestTypeListBuilder',
      'route_provider' => [
        'html' => 'Drupal\Core\Entity\Routing\AdminHtmlRouteProvider',
      ],
    ],
    'admin_permission' => 'administer translation request types',
    'bundle_of' => 'oe_translation_request',
    'config_prefix' => 'oe_translation_request_type',
    'entity_keys' => [
      'id' => 'id',
      'label' => 'label',
      'uuid' => 'uuid',
    ],
    'links' => [
      'add-form' => '/admin/structure/oe_translation_request_types/add',
      'edit-form' => '/admin/structure/oe_translation_request_types/manage/{oe_translation_request_type}',
      'delete-form' => '/admin/structure/oe_translation_request_types/manage/{oe_translation_request_type}/delete',
      'collection' => '/admin/structure/oe_translation_request_types',
    ],
    'config_export' => [
      'id',
      'label',
      'uuid',
    ],
  ];
  $translation_request = new ContentEntityType($translation_request_entity_type);
  $translation_request->setClass(TranslationRequest::class);
  $update_manager->installEntityType($translation_request);

  $translation_request_type = new ConfigEntityType($translation_request_config_entity_type);
  $translation_request_type->setClass(TranslationRequestType::class);
  $update_manager->installEntityType($translation_request_type);

  $translation_request_log = new ContentEntityType($translation_request_log_entity_type);
  $translation_request_log->setClass(TranslationRequestLog::class);
  $update_manager->installEntityType($translation_request_log);

}

/**
 * Add index to all fields of type oe_translation_language_with_entity_revision.
 */
function oe_translation_update_9002(): void {
  /** @var \Drupal\Core\Entity\EntityFieldManager $field_manager */
  $field_manager = \Drupal::service('entity_field.manager');
  $definition_manager = \Drupal::entityDefinitionUpdateManager();
  $database = \Drupal::database();
  $entity_type_manager = \Drupal::entityTypeManager();
  $field_type = 'oe_translation_language_with_entity_revision';
  // Get all field storage configs for this field type.
  $field_storage_configs = \Drupal::entityTypeManager()
    ->getStorage('field_storage_config')
    ->loadByProperties(['type' => $field_type]);

  foreach ($field_storage_configs as $field_storage) {
    $field_name = $field_storage->getName();
    $entity_type_id = $field_storage->getTargetEntityTypeId();
    $storage = $entity_type_manager->getStorage($entity_type_id);
    $table_mapping = $storage->getTableMapping();
    $table_name = $table_mapping->getFieldTableName($field_name);
    $table_schema = $field_storage->getSchema();
    $spec_properties = ['entity_type', 'entity_id'];
    $index_columns = [
      $field_name . '_entity_type',
      $field_name . '_entity_id',
    ];

    $spec = [];
    $column_number = count($index_columns);
    for ($i = 0; $i < $column_number; $i++) {
      $id = $index_columns[$i];
      $property = $spec_properties[$i];
      if (isset($table_schema['columns'][$property])) {
        $spec[$id] = $table_schema['columns'][$property];
      }
    }

    // Add index to data table.
    if (!$database->schema()->indexExists($table_name, 'idx_revision_lookup')) {
      $database->schema()->addIndex(
        $table_name,
        'idx_revision_lookup',
        $index_columns,
        ['fields' => $spec]
      );
    }

    $field_manager->clearCachedFieldDefinitions();
    $field_storage = $definition_manager->getFieldStorageDefinition($field_name, $entity_type_id);
    $definition_manager->updateFieldStorageDefinition($field_storage);
  }
}

/**
 * Add index to oe_translation_request.
 */
function oe_translation_update_9003(): void {
  /** @var \Drupal\Core\Entity\EntityFieldManager $field_manager */
  $field_manager = \Drupal::service('entity_field.manager');
  $definition_manager = \Drupal::entityDefinitionUpdateManager();
  $field_storage_definitions = $field_manager->getFieldStorageDefinitions('oe_translation_request');
  if (isset($field_storage_definitions['content_entity'])) {
    \Drupal::service('entity.last_installed_schema.repository')
      ->setLastInstalledFieldStorageDefinition($field_storage_definitions['content_entity']);
  }

  $field_storage = $definition_manager->getFieldStorageDefinition('content_entity', 'oe_translation_request');
  $definition_manager->updateFieldStorageDefinition($field_storage);
}
