<?php

/**
 * @file
 * OpenEuropa Translation module file.
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\oe_translation\Entity\TranslationRequestInterface;
use Drupal\oe_translation\Entity\TranslationRequestLogInterface;
use Drupal\oe_translation\TranslationModerationHandler;
use Drupal\oe_translation\TranslationSourceFieldProcessor\AddressFieldProcessor;
use Drupal\oe_translation\TranslationSourceFieldProcessor\DefaultFieldProcessor;
use Drupal\oe_translation\TranslationSourceFieldProcessor\DescriptionListFieldProcessor;
use Drupal\oe_translation\TranslationSourceFieldProcessor\MetatagsFieldProcessor;
use Drupal\oe_translation\TranslationSourceFieldProcessor\PathFieldProcessor;

/**
 * Implements hook_theme().
 */
function oe_translation_theme($existing, $type, $theme, $path) {
  return [
    'local_translation_form_element_group' => [
      'render element' => 'element',
    ],
    'tooltip' => [
      'variables' => [
        'text' => NULL,
        'label' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function oe_translation_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type_id => $entity_type) {
    // Set translator providers.
    if ($entity_type_id === 'node') {
      $translators = [
        'local' => TRUE,
        'remote' => [
          'epoetry',
        ],
      ];
      $entity_type->set('oe_translation_translators', $translators);
    }

    // Change the moderation handler if set to our own override.
    if (!$entity_type->hasHandlerClass('moderation')) {
      continue;
    }

    $entity_type->setHandlerClass('moderation', TranslationModerationHandler::class);
  }
}

/**
 * Implements template_preprocess_node().
 */
function oe_translation_preprocess_node(&$variables) {
  // Ensure that on the preview page, we treat the node as the full page
  // display.
  if (\Drupal::service('current_route_match')->getRouteName() !== 'entity.oe_translation_request.preview') {
    return;
  }

  $variables['page'] = TRUE;
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function oe_translation_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  // We don't want different translations to have different moderation states
  // so we make the moderation state field untranslatable.
  if ($entity_type->id() === 'content_moderation_state') {
    $fields['moderation_state']->setTranslatable(FALSE);
  }
}

/**
 * Implements hook_entity_access().
 */
function oe_translation_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if (!$entity instanceof ContentEntityInterface) {
    return AccessResult::neutral();
  }

  if (!in_array($operation, ['update'])) {
    // @todo , see if we should allow the deletion of translations.
    return AccessResult::neutral();
  }

  /** @var \Drupal\oe_translation\TranslatorProvidersInterface $translator_providers */
  $translator_providers = \Drupal::service('oe_translation.translator_providers');
  if (!$translator_providers->hasTranslators($entity->getEntityType())) {
    return AccessResult::neutral();
  }

  // We do not want translations to be manually edited if they are supported
  // by our translation system and the local translation is disabled.
  if (!$entity->isDefaultTranslation() && $translator_providers->hasLocal($entity->getEntityType())) {
    return AccessResult::forbidden()->addCacheableDependency($entity);
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_field_info_alter().
 */
function oe_translation_field_info_alter(&$info) {
  if (isset($info['metatag'])) {
    $info['metatag']['oe_translation_source_field_processor'] = MetatagsFieldProcessor::class;
  }
  if (isset($info['path'])) {
    $info['path']['oe_translation_source_field_processor'] = PathFieldProcessor::class;
  }
  if (isset($info['address'])) {
    $info['address']['oe_translation_source_field_processor'] = AddressFieldProcessor::class;
  }
  if (isset($info['description_list_field'])) {
    $info['description_list_field']['oe_translation_source_field_processor'] = DescriptionListFieldProcessor::class;
  }
  if (isset($info['typed_link'])) {
    $info['typed_link']['column_groups'] = [
      'uri' => [
        'label' => t('URI'),
        'translatable' => TRUE,
      ],
      'title' => [
        'label' => t('Title'),
        'translatable' => TRUE,
      ],
      'options' => [
        'label' => t('Options'),
        'translatable' => FALSE,
      ],
      'link_type' => [
        'label' => t('Link type'),
        'translatable' => TRUE,
      ],
    ];
  }

  // Set a default processor class for all fields that do not have one yet.
  foreach ($info as &$field_type) {
    if (!isset($field_type['oe_translation_source_field_processor'])) {
      $field_type['oe_translation_source_field_processor'] = DefaultFieldProcessor::class;
    }
  }
}

/**
 * Implements template_preprocess_local_translation_form_element_group().
 *
 * Template responsible for rendering the local translation form elements.
 */
function oe_translation_preprocess_local_translation_form_element_group(&$variables) {
  $element = $variables['element'];

  $table = [
    '#type' => 'table',
    '#attributes' => [
      'id' => $element['#ajaxid'],
    ],
    '#header' => [
      [
        'data' => implode(' / ', $element['#parent_label']),
        'colspan' => 2,
      ],
    ],
    '#rows' => [],
  ];

  $rows = [];
  $rows[] = [
    [
      'data' => $element['source'],
    ],
    [
      'data' => $element['translation'],
    ],
  ];

  $table['#rows'] = $rows;

  $variables['element'] = $table;
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter() for the Page Header block.
 */
function oe_translation_block_view_oe_theme_helper_page_header_alter(array &$build, $block) {
  $build['#pre_render'][] = function (array $build) {
    // This block is shipped by OpenEuropa Theme and we use this to remove the
    // language switcher from the page header on the entity preview page.
    if (\Drupal::service('current_route_match')->getRouteName() !== 'entity.oe_translation_request.preview') {
      return $build;
    }

    if (isset($build['content']['#language_switcher'])) {
      unset($build['content']['#language_switcher']);
    }

    return $build;
  };
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function oe_translation_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  // Prepare some basic breadcrumb links for the translation request entities.
  if ($route_match->getRouteName() === 'entity.oe_translation_request.canonical') {
    _oe_translation_default_breadcrumb_links($breadcrumb, $route_match, $context);
  }
}

/**
 * Prepares base breadcrumb links for translation pages.
 *
 * @param \Drupal\Core\Breadcrumb\Breadcrumb $breadcrumb
 *   The breadcrumb.
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *   The route match.
 * @param array $context
 *   The context.
 */
function _oe_translation_default_breadcrumb_links(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context): void {
  $links = [];
  $links[] = Link::fromTextAndUrl(t('Home'), Url::fromRoute('<front>'));
  /** @var \Drupal\oe_translation\Entity\TranslationRequestInterface $translation_request */
  $translation_request = $route_match->getParameter('oe_translation_request');
  $entity = $translation_request->getContentEntity();
  $links[] = $entity->toLink();
  $links[] = Link::fromTextAndUrl(t('Translate'), $entity->toUrl('drupal:content-translation-overview'));
  $cache = CacheableMetadata::createFromObject($breadcrumb);
  $cache->addCacheContexts(['route']);
  $breadcrumb = new Breadcrumb();
  $breadcrumb->addCacheableDependency($cache);
  $breadcrumb->setLinks($links);
}

/**
 * Creates a table of log messages for the request.
 *
 * @param \Drupal\oe_translation\Entity\TranslationRequestInterface $request
 *   The request.
 *
 * @return array
 *   The log messages.
 */
function _oe_translation_create_request_logs_tables(TranslationRequestInterface $request): array {
  $logs = $request->getLogMessages();
  if (!$logs) {
    return [];
  }

  $table = [
    '#type' => 'table',
    '#attributes' => [
      'class' => ['translation-request-log-messages'],
    ],
    '#header' => [
      '#',
      t('Type'),
      t('Message'),
      t('User'),
      t('Date'),
    ],
  ];

  $rows = [];
  $i = 1;
  foreach ($logs as $log) {
    $class_map = [
      TranslationRequestLogInterface::ERROR => 'color-error',
      TranslationRequestLogInterface::WARNING => 'color-warning',
    ];
    $class = $class_map[$log->getType()] ?? NULL;
    $row = [
      $i,
      ucfirst($log->getType()),
      $log->getMessage(),
      [
        'data' => [
          '#theme' => 'username',
          '#account' => $log->getOwner(),
          '#cache' => [
            'tags' => $log->getOwner()->getCacheTags(),
          ],
        ],
      ],
      \Drupal::service('date.formatter')->format($log->getCreatedTime(), 'short'),
    ];
    $rows[] = [
      'data' => $row,
      'class' => $class ? [$class] : [],
    ];
    $i++;
  }

  $table['#rows'] = $rows;
  return $table;
}

/**
 * Implements hook_entity_operation_alter().
 */
function oe_translation_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if (!$entity instanceof TranslationRequestInterface) {
    return;
  }

  if (isset($operations['edit'])) {
    // Remove the edit operation because for the moment we won't edit requests.
    unset($operations['edit']);
  }

  // Add the extra operations we are defining with our subscriber.
  foreach ($entity->getOperationsLinks()['#links'] as $op => $link) {
    if (!isset($operations[$op])) {
      $operations[$op] = $link;
    }
  }
}

/**
 * Implements template_preprocess_tooltip().
 */
function oe_translation_preprocess_tooltip(array &$variables) {
  $variables['#attached']['library'][] = 'oe_translation/tooltip';
}

/**
 * Implements hook_entity_base_field_info().
 *
 * We are keeping the 2 tmgmt_job and tmgmt_job_item base fields in place until
 * the 2.x version of the translations system is deployed.
 */
function oe_translation_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'tmgmt_job_item') {
    $fields = [];
    // Add a field to the Job item to store the entity revision at the moment of
    // creation.
    $fields['item_rid'] = BaseFieldDefinition::create('integer')
      ->setLabel(new TranslatableMarkup('Item revision ID'))
      ->setSetting('unsigned', TRUE);
    // Add a field to the Job item to store the entity bundle being translated.
    // This is needed to be able to inspect field related info if the entity
    // itself gets deleted.
    $fields['item_bundle'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Item bundle'));
    return $fields;
  }

  if ($entity_type->id() === 'tmgmt_job') {
    $fields = [];
    $fields['poetry_request_id'] = BaseFieldDefinition::create('poetry_request_id')
      ->setLabel(t('The Poetry request ID'))
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'poetry_request_id_formatter',
        'weight' => 20,
      ]);

    $fields['poetry_state'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Poetry state'))
      ->setDescription(t('The poetry job state while the job is active.'))
      ->setSetting('allowed_values', [
        'ongoing' => t('Ongoing'),
        'translated' => t('Translated'),
      ]);

    $fields['poetry_request_date'] = BaseFieldDefinition::create('datetime')
      ->setLabel(t('The Poetry request date'))
      ->setDescription(t('The date when the translations are expected at the moment of the request.'));

    $fields['poetry_request_date_updated'] = BaseFieldDefinition::create('datetime')
      ->setLabel(t('The Poetry updated request date'))
      ->setDescription(t('The updated date when the translations are expected. Poetry can choose to update the request with a new expected delivery date.'));

    return $fields;
  }
}
