<?php

/**
 * @file
 * Module file of the OpenEuropa DGT HTML formatter.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_translation_poetry_html_formatter_theme() {
  return [
    'poetry_html_template' => [
      'variables' => [
        'entity_id' => NULL,
        'source_language' => NULL,
        'target_language' => NULL,
        'items' => NULL,
      ],
    ],
  ];
}
