<?php

/**
 * @file
 * The OE Translation Test module.
 */

declare(strict_types = 1);

use Drupal\oe_translation_test\TranslationHandler;

/**
 * Implements hook_entity_type_alter().
 */
function oe_translation_test_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $entity_type */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type->hasHandlerClass('oe_translation')) {
      $entity_type->setHandlerClass('oe_translation', TranslationHandler::class);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function oe_translation_test_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'entity_type_alter':
      $group = $implementations['oe_translation_test'];
      unset($implementations['oe_translation_test']);
      $implementations['oe_translation_test'] = $group;
      break;
  }
}
