<?php

/**
 * @file
 * OpenEuropa Translation Poetry module file.
 */

declare(strict_types = 1);

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\oe_translation_poetry\JobItemListBuilder;
use Drupal\Core\Access\AccessResult;
use Drupal\tmgmt\Entity\Job;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\oe_translation_poetry\Plugin\tmgmt\Translator\PoetryTranslator;

/**
 * Implements hook_poetry_entity_type_alter().
 */
function oe_translation_poetry_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $entity_type */
  $entity_type = $entity_types['tmgmt_job_item'] ?? NULL;
  if ($entity_type) {
    $entity_type->setHandlerClass('list_builder', JobItemListBuilder::class);
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function oe_translation_poetry_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'tmgmt_job') {
    $fields = [];
    $fields['poetry_request_id'] = BaseFieldDefinition::create('poetry_request_id')
      ->setLabel(t('The Poetry request ID'))
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'poetry_request_id_formatter',
        'weight' => 20,
      ]);

    $fields['poetry_state'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Poetry state'))
      ->setDescription(t('The poetry job state while the job is active.'))
      ->setSetting('allowed_values', [
        PoetryTranslator::POETRY_STATUS_ONGOING => t('Ongoing'),
        PoetryTranslator::POETRY_STATUS_TRANSLATED => t('Translated'),
      ]);

    $fields['poetry_request_date'] = BaseFieldDefinition::create('datetime')
      ->setLabel(t('The Poetry request date'))
      ->setDescription(t('The date when the translations are expected at the moment of the request.'));

    $fields['poetry_request_date_updated'] = BaseFieldDefinition::create('datetime')
      ->setLabel(t('The Poetry updated request date'))
      ->setDescription(t('The updated date when the translations are expected. Poetry can choose to update the request with a new expected delivery date.'));

    return $fields;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the TMGMT content overview form.
 */
function oe_translation_poetry_form_tmgmt_content_translate_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $poetry = \Drupal::service('plugin.manager.tmgmt.translator')->createInstance('poetry');
  $form['actions']['request']['#submit'] = [];
  $form['actions']['request']['#submit'][] = [$poetry, 'submitPoetryTranslationRequest'];

  // If we have jobs in the current job queue, we want to disable all the
  // checkboxes for choosing languages to translate. The user should first
  // either clear the existing jobs or finalize the request.
  /** @var \Drupal\oe_translation_poetry\PoetryJobQueueFactory $job_queue_factory */
  $job_queue_factory = \Drupal::service('oe_translation_poetry.job_queue_factory');
  $entity = $form_state->get('entity');
  $job_queue = $job_queue_factory->get($entity);
  if (!empty($job_queue->getAllJobs())) {
    // Remove validation since we just need to be redirected to the checkout
    // form regardless.
    $form['#validate'] = [];
    // Disable the checkboxes in the tableselect.
    foreach ($form['languages']['#options'] as $langcode => $option) {
      $form['languages'][$langcode] = [
        '#type' => 'checkbox',
        '#disabled' => TRUE,
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for the Job entity.
 */
function oe_translation_poetry_tmgmt_job_presave(EntityInterface $entity) {
  // If the state of the job is not active, we should not have any value in the
  // custom Poetry state field.
  /** @var \Drupal\tmgmt\JobInterface $entity */
  if ((int) $entity->getState() !== Job::STATE_ACTIVE) {
    $entity->set('poetry_state', NULL);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access() for the TMGMT job items.
 */
function oe_translation_poetry_tmgmt_job_item_access(EntityInterface $entity, $operation, AccountInterface $account) {
  /** @var \Drupal\tmgmt\JobItemInterface $entity */
  $job = $entity->getJob();
  if (!$job->getTranslatorPlugin() instanceof PoetryTranslator) {
    return AccessResult::neutral();
  }

  if ($operation === 'abort') {
    // We don't want to abort jobs items.
    return AccessResult::forbidden();
  }

  if ($operation !== 'update') {
    return AccessResult::neutral();
  }

  if ($job->get('poetry_state')->value !== PoetryTranslator::POETRY_STATUS_TRANSLATED) {
    // Forbid access to job item updates if they have not been translated by
    // Poetry.
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for the Node confirm delete form.
 */
function oe_translation_poetry_form_node_confirm_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // If the user is trying to delete a node, we should show a warning that
  // there are ongoing translation jobs associated with it.
  $node = \Drupal::service('current_route_match')->getParameter('node');
  if (!$node instanceof NodeInterface) {
    return;
  }

  $query = \Drupal::database()->select('tmgmt_job', 'job');
  $query->join('tmgmt_job_item', 'job_item', 'job.tjid = job_item.tjid');
  $query->fields('job', ['tjid', 'target_language']);
  $query->fields('job_item', ['tjiid']);
  $query->condition('job_item.item_id', $node->id());
  $query->condition('job.translator', 'poetry', '=');
  $query->condition('job.poetry_state', PoetryTranslator::POETRY_STATUS_ONGOING, '=');

  $result = $query->execute()->fetchAllAssoc('target_language');
  if (!$result) {
    return;
  }

  \Drupal::messenger()->addWarning(t('This node has ongoing translation jobs associated in Poetry. Ongoing requests cannot be automatically cancelled, please inform DGT about your cancellation request.'));
}
