<?php

/**
 * @file
 * Menu link content translation test module.
 */

/**
 * Implements hook_entity_type_alter().
 */
function oe_translation_menu_link_test_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $entity_type */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type_id === 'menu_link_content') {
      $translators = [
        'remote' => [
          'remote_one',
        ],
      ];

      $entity_type->set('oe_translation_translators', $translators);
    }
  }
}
