<?php

declare(strict_types=1);

namespace Drupal\oe_translation_etrans\Event;

use Drupal\oe_translation_etrans\TranslationRequestEtransInterface;
use Symfony\Contracts\EventDispatcher\Event;

/**
 * Event for resolving the translation request from the request ID.
 */
class EtransTranslationRequestResolverEvent extends Event {

  /**
   * The request ID generated by DGT.
   *
   * @var string
   */
  protected string $requestId;

  /**
   * The access token from Etrans to securely identify the request.
   *
   * @var string|null
   */
  protected string|null $token;

  /**
   * The translation request that may have been resolved.
   *
   * @var null|TranslationRequestEtransInterface
   */
  protected ?TranslationRequestEtransInterface $request;

  /**
   * Constructs a EtransTranslationRequestResolverEvent.
   *
   * @param string $requestId
   *   The request ID generated by DGT.
   * @param string|null $token
   *   The token.
   */
  public function __construct(string $requestId, string|null $token) {
    $this->requestId = $requestId;
    $this->token = $token;
  }

  /**
   * Returns the request ID.
   *
   * @return string
   *   The request ID.
   */
  public function getRequestId(): string {
    return $this->requestId;
  }

  /**
   * Returns the token.
   *
   * @return string|null
   *   The token.
   */
  public function getToken(): ?string {
    return $this->token;
  }

  /**
   * Returns the translation request.
   *
   * @return \Drupal\oe_translation_etrans\TranslationRequestEtransInterface|null
   *   The translation request.
   */
  public function getRequest(): ?TranslationRequestEtransInterface {
    return $this->request;
  }

  /**
   * Sets the translation request.
   *
   * @param \Drupal\oe_translation_etrans\TranslationRequestEtransInterface|null $request
   *   The translation request.
   */
  public function setRequest(?TranslationRequestEtransInterface $request): void {
    $this->request = $request;
  }

}
