<?php

declare(strict_types=1);

namespace Drupal\oe_translation_etrans\Event;

use Drupal\oe_translation_etrans\TranslationRequestEtransInterface;
use Symfony\Contracts\EventDispatcher\Event;

/**
 * Event dispatched when a translation is being delivered.
 */
class EtransDeliveryEvent extends Event {

  /**
   * The request ID generated by DGT.
   *
   * @var string
   */
  protected string $requestId;

  /**
   * The language for which the translation is being delivered.
   *
   * @var string
   */
  protected string $language;

  /**
   * The translation HTML string.
   *
   * @var string
   */
  protected string $translation;

  /**
   * The translation request.
   *
   * @var \Drupal\oe_translation_etrans\TranslationRequestEtransInterface
   */
  protected $translationRequest;

  /**
   * Constructs a EtransDeliveryEvent.
   *
   * @param string $requestId
   *   The request ID generated by DGT.
   * @param string $language
   *   The language for which the translation is being delivered.
   * @param string $translation
   *   The translation HTML string.
   * @param \Drupal\oe_translation_etrans\TranslationRequestEtransInterface $translationRequest
   *   The translation request.
   */
  public function __construct(string $requestId, string $language, string $translation, TranslationRequestEtransInterface $translationRequest) {
    $this->requestId = $requestId;
    $this->translation = $translation;
    $this->language = $language;
    $this->translationRequest = $translationRequest;
  }

  /**
   * Returns the request ID.
   *
   * @return string
   *   The request ID
   */
  public function getRequestId(): string {
    return $this->requestId;
  }

  /**
   * Returns the translation.
   *
   * @return string
   *   The translation.
   */
  public function getTranslation(): string {
    return $this->translation;
  }

  /**
   * Returns the language code.
   *
   * @return string
   *   The language code.
   */
  public function getLanguage(): string {
    return $this->language;
  }

  /**
   * Returns the translation request.
   *
   * @return \Drupal\oe_translation_etrans\TranslationRequestEtransInterface
   *   The translation request.
   */
  public function getTranslationRequest(): TranslationRequestEtransInterface {
    return $this->translationRequest;
  }

}
