<?php

declare(strict_types=1);

namespace Drupal\oe_translation_etrans\Event;

use Symfony\Contracts\EventDispatcher\Event;

/**
 * Event dispatched when we receive a failure notification.
 */
class EtransFailureEvent extends Event {

  /**
   * The request ID generated by DGT.
   *
   * @var string
   */
  protected string $requestId;

  /**
   * The error code.
   *
   * @var string
   */
  protected string $errorCode;

  /**
   * The error message.
   *
   * @var string
   */
  protected string $errorMessage;

  /**
   * The target languages.
   *
   * @var array
   */
  protected array $targetLanguages;

  /**
   * Constructs a EtransDeliveryEvent.
   *
   * @param string $requestId
   *   The request ID generated by DGT.
   * @param string $errorCode
   *   The error code.
   * @param string $errorMessage
   *   The error message.
   * @param array $targetLanguages
   *   The target languages.
   */
  public function __construct(string $requestId, string $errorCode, string $errorMessage, array $targetLanguages = []) {
    $this->requestId = $requestId;
    $this->errorCode = $errorCode;
    $this->errorMessage = $errorMessage;
    $this->targetLanguages = $targetLanguages;
  }

  /**
   * Returns the request ID.
   *
   * @return string
   *   The request ID
   */
  public function getRequestId(): string {
    return $this->requestId;
  }

  /**
   * Returns the error code.
   *
   * @return string
   *   The error code.
   */
  public function getErrorCode(): string {
    return $this->errorCode;
  }

  /**
   * Returns the error message.
   *
   * @return string
   *   The error message.
   */
  public function getErrorMessage(): string {
    return $this->errorMessage;
  }

  /**
   * Returns the target languages.
   *
   * @return array
   *   The target languages.
   */
  public function getTargetLanguages(): array {
    return $this->targetLanguages;
  }

}
