name: ci
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 3.x

jobs:
  automated-tests:
    uses: openeuropa/github-ci/.github/workflows/drupal-ci.yml@EWPP-6514-1
    with:
      run_behat: false
